from flask import Flask, render_template, request, jsonify, send_file
from flask_cors import CORS
import base64
import mimetypes
import os
from google import genai
from google.genai import types
from PIL import Image
import io
from dotenv import load_dotenv
from datetime import datetime

load_dotenv()

app = Flask(__name__, static_folder='static', static_url_path='/static')
CORS(app)

# Create output directory if it doesn't exist
OUTPUT_DIR = "outputs"
os.makedirs(OUTPUT_DIR, exist_ok=True)


def get_mime_type(filename):
    """Get MIME type from filename"""
    mime_type, _ = mimetypes.guess_type(filename)
    return mime_type or 'image/jpeg'


def generate_dress_change(person_image_bytes, person_filename, costume_image_bytes, costume_filename):
    """Generate dress change using Gemini API"""
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise ValueError("GEMINI_API_KEY not found in environment variables")

    client = genai.Client(api_key=api_key)
    model = "gemini-2.5-flash-image-preview"

    # Get MIME types
    person_mime = get_mime_type(person_filename)
    costume_mime = get_mime_type(costume_filename)

    contents = [
        types.Content(
            role="user",
            parts=[
                types.Part.from_text(text="""You are a virtual try-on assistant. Please replace the clothing worn by the person in the first image with the clothing item shown in the second image. 

Instructions:
1. Completely remove the existing clothing/garment that would be replaced by the new item
2. Fit the new clothing naturally on the person's body, maintaining proper proportions and perspective
3. Preserve the person's face, skin tone, hair, body pose, and background exactly as they appear
4. Match the lighting, shadows, and overall atmosphere of the original photo
5. Ensure the new clothing looks realistic with appropriate wrinkles, folds, and texture
6. Make sure the clothing fits the person's body type naturally

Generate a high-quality, photorealistic result."""),
                types.Part(
                    inline_data=types.Blob(
                        mime_type=person_mime,
                        data=person_image_bytes
                    )
                ),
                types.Part(
                    inline_data=types.Blob(
                        mime_type=costume_mime,
                        data=costume_image_bytes
                    )
                ),
            ],
        ),
    ]

    generate_content_config = types.GenerateContentConfig(
        response_modalities=["IMAGE", "TEXT"],
    )

    # Generate content
    for chunk in client.models.generate_content_stream(
            model=model,
            contents=contents,
            config=generate_content_config,
    ):
        if (
                chunk.candidates is None
                or chunk.candidates[0].content is None
                or chunk.candidates[0].content.parts is None
        ):
            continue

        for part in chunk.candidates[0].content.parts:
            if part.inline_data and part.inline_data.data:
                inline_data = part.inline_data
                data_buffer = inline_data.data

                # Convert to JPEG if needed
                if inline_data.mime_type != "image/jpeg":
                    img = Image.open(io.BytesIO(data_buffer))
                    if img.mode in ("RGBA", "P"):
                        img = img.convert("RGB")

                    jpeg_buffer = io.BytesIO()
                    img.save(jpeg_buffer, format="JPEG", quality=95)
                    data_buffer = jpeg_buffer.getvalue()

                # Save with timestamp
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                output_path = os.path.join(OUTPUT_DIR, f"result_{timestamp}.jpg")

                with open(output_path, "wb") as f:
                    f.write(data_buffer)

                return output_path

    raise Exception("No image was generated by the model")


@app.route('/')
def index():
    return render_template('index.html')

@app.route('/integrated')
def integrated():
    """Serve the integrated fashion scraper + virtual try-on page"""
    return render_template('integrated.html')

@app.route('/test-static')
def test_static():
    """Test route to verify static files are being served"""
    return f"""
    <h1>Static Files Test</h1>
    <p>CSS: <a href="/static/modern.css">/static/modern.css</a></p>
    <p>JS: <a href="/static/modern.js">/static/modern.js</a></p>
    <p>If these links work, static files are being served correctly.</p>
    """


@app.route('/generate', methods=['POST'])
def generate():
    try:
        # Check if files are present
        if 'personImage' not in request.files or 'costumeImage' not in request.files:
            return jsonify({'error': 'Both images are required'}), 400

        person_image = request.files['personImage']
        costume_image = request.files['costumeImage']

        if person_image.filename == '' or costume_image.filename == '':
            return jsonify({'error': 'Both images must be selected'}), 400

        # Read the file contents once
        person_image_bytes = person_image.read()
        costume_image_bytes = costume_image.read()

        # Generate the image
        output_path = generate_dress_change(
            person_image_bytes,
            person_image.filename,
            costume_image_bytes,
            costume_image.filename
        )

        # Read the generated image and convert to base64
        with open(output_path, 'rb') as f:
            image_data = base64.b64encode(f.read()).decode('utf-8')

        return jsonify({
            'success': True,
            'image': f'data:image/jpeg;base64,{image_data}',
            'filename': os.path.basename(output_path)
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500


def run_virtual_try_on_server(port=5001, debug=True):
    """Run the virtual try-on Flask server"""
    app.run(host='127.0.0.1', port=port, debug=debug, use_reloader=False)


if __name__ == '__main__':
    run_virtual_try_on_server()

